# Generated by Django 5.2.6 on 2025-09-12 03:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters_name', models.CharField(max_length=100)),
                ('chapters_cover', models.ImageField(upload_to='media/chapters/cover')),
                ('chairman_name', models.CharField(max_length=100)),
                ('chairman_pic', models.ImageField(upload_to='media/chapters/chairman')),
                ('co_chairman_name', models.CharField(max_length=100)),
                ('co_chairman_pic', models.ImageField(upload_to='media/chapters/co_chairman')),
                ('secretary_name', models.CharField(max_length=100)),
                ('secretary_pic', models.ImageField(upload_to='media/chapters/secretary')),
                ('financial_secretary_name', models.CharField(max_length=100)),
                ('financial_secretary_pic', models.ImageField(upload_to='media/chapters/financial_secretary')),
                ('treasurer_name', models.CharField(max_length=100)),
                ('treasurer_pic', models.ImageField(upload_to='media/chapters/treasurer')),
                ('chaplain_name', models.CharField(max_length=100)),
                ('chaplain_pic', models.ImageField(upload_to='media/chapters/chaplain')),
                ('training_director_name', models.CharField(max_length=100)),
                ('training_director_pic', models.ImageField(upload_to='media/chapters/training_director')),
                ('program_director_name', models.CharField(max_length=100)),
                ('program_director_pic', models.ImageField(upload_to='media/chapters/program_director')),
                ('parliamentarian_name', models.CharField(max_length=100)),
                ('parliamentarian_pic', models.ImageField(upload_to='media/chapters/parliamentarian')),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_pic', models.ImageField(upload_to='media/chapters/reporter')),
                ('girl_in_ict_name', models.CharField(max_length=100)),
                ('girl_in_ict_pic', models.ImageField(upload_to='media/chapters/girl_in_ict')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(blank=True, max_length=100, null=True)),
                ('president_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('vic_president', models.CharField(blank=True, max_length=100, null=True)),
                ('vic_president_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('financial_secretary', models.CharField(blank=True, max_length=100, null=True)),
                ('financial_secretary_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('secretary_general', models.CharField(blank=True, max_length=100, null=True)),
                ('secretary_general_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('aLL_chapters_chairman', models.CharField(blank=True, max_length=100, null=True)),
                ('aLL_chapters_chairma_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('program_director', models.CharField(blank=True, max_length=100, null=True)),
                ('program_director_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('training_director', models.CharField(blank=True, max_length=100, null=True)),
                ('training_director_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('sa', models.CharField(blank=True, max_length=100, null=True)),
                ('sa_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('girls_in_ICTs_chairlady', models.CharField(blank=True, max_length=100, null=True)),
                ('girls_in_ICTs_chairlady_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('national_reporter', models.CharField(blank=True, max_length=100, null=True)),
                ('national_reporter_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('systems_administrator', models.CharField(blank=True, max_length=100, null=True)),
                ('systems_administrator_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('p_r_o', models.CharField(blank=True, max_length=100, null=True)),
                ('p_r_o_cover', models.ImageField(blank=True, null=True, upload_to='media/leadership/cover')),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership_From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='media/membership/profile_pic')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('county_of_residence', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('extra_skill', models.CharField(max_length=100)),
                ('level_of_education', models.CharField(max_length=100)),
                ('chapter_name', models.CharField(blank=True, max_length=100)),
                ('living_with', models.CharField(max_length=10)),
                ('working_or_not', models.CharField(blank=True, max_length=3)),
                ('if_yes_place_of_work', models.CharField(blank=True, max_length=100)),
                ('hear_about_us', models.CharField(max_length=100)),
                ('why_be_member', models.TextField()),
                ('emergency_first_name', models.CharField(max_length=100)),
                ('emergency_last_name', models.CharField(max_length=100)),
                ('emergency_email', models.EmailField(max_length=254)),
                ('emergency_address', models.TextField()),
                ('emergency_relationship', models.CharField(max_length=100)),
                ('accepted_membership_rules', models.BooleanField(default=False)),
                ('accepted_privacy_policy', models.BooleanField(default=False)),
                ('payment_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin1'), (4, 'Editors')], default=1, max_length=58)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter_Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=200)),
                ('chapter_chairman_name', models.CharField(max_length=200)),
                ('chapter_chairman_cover', models.ImageField(upload_to='media/leadership/cover')),
                ('leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leaderships')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images/')),
                ('category', models.CharField(blank=True, choices=[('News', 'News'), ('Announcements', 'Announcements')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
