# Generated by Django 5.2.6 on 2025-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='image',
            field=models.ImageField(upload_to='Programs_images/'),
        ),
    ]
