# Generated by Django 5.2.6 on 2025-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_programs_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidential_info', models.CharField(max_length=100)),
                ('president_image', models.ImageField(upload_to='media/Presidential/pic')),
                ('vice_president_image', models.ImageField(upload_to='media/Presidential/pic')),
                ('year', models.CharField(max_length=100)),
            ],
        ),
    ]
