# Generated by Django 5.2.6 on 2025-09-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_president'),
    ]

    operations = [
        migrations.AddField(
            model_name='president',
            name='president_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='president',
            name='vice_president_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
