# Generated by Django 5.2.6 on 2025-09-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_president_president_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chaplain_status',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
