# Generated by Django 5.2.6 on 2025-09-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chapter_chaplain_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chaplain_status',
            new_name='chapters_status',
        ),
    ]
