# Generated by Django 5.2.6 on 2025-09-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_chaplain_status_chapter_chapters_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapters_status',
            field=models.CharField(blank=True, choices=[('Liberian_Chapters', 'Liberian_Chapters'), ('International_Chapters', 'International_Chapters')], max_length=100),
        ),
    ]
