# Generated by Django 5.2.6 on 2025-09-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_chapter_chapters_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='year',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
