# Generated by Django 5.2.6 on 2025-09-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_chapter_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='year',
        ),
    ]
