# Generated by Django 5.2.6 on 2025-09-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_chapter_national_champlain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='national_champlain',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='national_champlain_pic',
        ),
        migrations.AddField(
            model_name='leaderships',
            name='national_champlain',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderships',
            name='national_champlain_pic',
            field=models.ImageField(default=2, upload_to='media/chapters/girl_in_ict'),
            preserve_default=False,
        ),
    ]
