# Generated by Django 5.2.6 on 2025-09-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_chapter_national_champlain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderships',
            name='national_champlain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaderships',
            name='national_champlain_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/leadership/cover'),
        ),
    ]
