# Generated by Django 5.2.6 on 2025-10-04 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_leaderships_national_champlain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership_from',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='membership_from',
            name='chapter_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.chapter'),
        ),
        migrations.AlterField(
            model_name='membership_from',
            name='extra_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='membership_from',
            name='living_with',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membership_from',
            name='profile_pic',
            field=models.ImageField(upload_to='membership/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='membership_from',
            name='working_or_not',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
